# env
- name: insert shell proxy(http)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes owner=root group=root mode=0644 regexp="export http_proxy={{ http_proxy }}"
              insertafter=EOF line="export http_proxy={{ http_proxy }}"
  ignore_errors: yes
  sudo: yes

- name: insert shell proxy(https)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes owner=root group=root mode=0644 regexp="export https_proxy={{ https_proxy }}"
              insertafter=EOF line="export https_proxy={{ https_proxy }}"
  ignore_errors: yes
  sudo: yes

- name: insert shell noproxy(http)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes owner=root group=root mode=0644 regexp="export no_proxy={{ no_proxy }}"
              insertafter=EOF line='export no_proxy="{{ no_proxy }}"'
  ignore_errors: yes
  sudo: yes
- name: insert shell ftp_proxy(ftp)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes owner=root group=root mode=0644 regexp="export ftp_proxy={{ http_proxy }}"
              insertafter=EOF line='export ftp_proxy="{{ http_proxy }}"'
  ignore_errors: yes
  sudo: yes

- name: insert proxies in sudoers
  lineinfile: dest=/etc/sudoers state=present regexp="Defaults    env_keep += \"http_proxy https_proxy ftp_proxy no_proxy\"" 
              line="Defaults    env_keep += \"http_proxy https_proxy ftp_proxy no_proxy\"" 
  ignore_errors: yes
  sudo: yes

#- name: insert docker proxy(http)
#  lineinfile: dest=/etc/default/docker state=present create=yes owner=root group=root mode=0644 regexp="export http_proxy={{ http_proxy }}"
#              insertafter=EOF line="export http_proxy={{ http_proxy }}"
#  ignore_errors: yes
#  sudo: yes
#
#- name: insert docker proxy(https)
#  lineinfile: dest=/etc/default/docker state=present create=yes owner=root group=root mode=0644 regexp="export https_proxy={{ https_proxy }}"
#              insertafter=EOF line="export https_proxy={{ https_proxy }}"
#  ignore_errors: yes
#  sudo: yes

#- name: insert docker noproxy(http)
#  lineinfile: dest=/etc/default/docker state=present create=yes owner=root group=root mode=0644 regexp="export no_proxy={{ no_proxy }}"
#              insertafter=EOF line='export no_proxy="{{ no_proxy }}"'
#  ignore_errors: yes
#  sudo: yes
#- name: insert docker ftp_proxy(ftp)
#  lineinfile: dest=/etc/default/docker state=present create=yes owner=root group=root mode=0644 regexp="export ftp_proxy={{ http_proxy }}"
#              insertafter=EOF line='export ftp_proxy="{{ http_proxy }}"'
#  ignore_errors: yes
#  sudo: yes



# git
#- name: set git proxy(http)
#  shell: "git config --global http.proxy {{ http_proxy }}"
#  ignore_errors: yes
#- name: set git proxy(https)
#  shell: "git config --global https.proxy {{ https_proxy }}"
#  ignore_errors: yes
## gem
#- name: insert gem proxy(http)
#  lineinfile: "dest=~/.gemrc state=present create=yes regexp='{{ http_proxy }}' insertafter=EOF line='http_proxy: {{ http_proxy }}'"
#  ignore_errors: yes
# wget
- name: install wget by yum
  yum: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - wget
- name: insert wget proxy(http)
  lineinfile: dest=/etc/wgetrc state=present regexp="{{ http_proxy }}"
              insertafter="^#http_proxy" line="http_proxy={{ http_proxy }}"
  ignore_errors: yes
  sudo: yes
- name: insert wget proxy(https)
  lineinfile: dest=/etc/wgetrc state=present regexp="{{ https_proxy }}"
              insertafter="^#https_proxy" line="https_proxy={{ https_proxy }}"
  ignore_errors: yes
  sudo: yes
# curl
- name: insert curl proxy(http)
  lineinfile: dest=/etc/.curlrc state=present create=yes regexp="{{ http_proxy }}"
              insertafter=EOF line="proxy={{ http_proxy }}"
  ignore_errors: yes
  sudo: yes
# yum
- name: insert yum proxy(http)
  lineinfile: dest=/etc/yum.conf state=present regexp="{{ http_proxy }}"
              insertafter=EOF line="proxy={{ http_proxy }}"
  ignore_errors: yes
  sudo: yes

#disablerepo="RHEL6Server_patchdate"
- name: yum update disablerepo="RHEL6Server_patchdate"
  yum: name="*" 
  sudo: yes
  ignore_errors: yes
