##      - common

- name: setup passwordless user
  lineinfile: dest=/etc/sudoers state=present regexp="{{ sudouser }}" ALL=(ALL) NOPASSWD: ALL" state=present
  sudo: yes
  tags:
     -  passwordlessudo



